import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          ITSC canned response loader
        </h1>

        <div id="catControl">
          <h2 className={styles.heady}>Your catagories</h2>
          <p><button>Add new catagory</button></p>
          <div>
            <button id="general">General</button>
          </div>
        </div>

        <div id="currentCats">
          <h2 className={styles.heady}>Choose response</h2>
          <button>hello</button>
          <button>googoo gaga</button>
        </div>

        <div id="options">
          <label className={styles.labelTtl} for="theirName">User's name</label>
          <input type="text" id="theirName"></input>
          <label className={styles.labelTtl} for="hEnding">happy ending?</label>
          <input type="checkbox" id="hEnding"></input>
          <button>Load!</button>
          
        </div>
      </main>

    </div>
  )
}
