import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          ITSC canned response loader
        </h1>

        <div id="catControl">
          <h2 className={styles.heady}>Your catagories</h2>
          <button id="newCat" className={styles.addBtn}>Add new catagory</button>
          <div className={styles.selektah}>
            <button id="general">General</button>
            <button>New accounts</button>
          </div>
        </div>

        <div id="currentCats">
          <h2 className={styles.heady}>Choose response</h2>
          <button id="newCat" className={styles.addBtn}>Add new catagory</button>
          <div className={styles.selektah}>
            <button>hello</button>
            <button>googoo gaga</button>

          </div>
        </div>

        <div id="options">
          <h2 className={styles.heady}>Choose options</h2>
          <div className={styles.optBox}>
            <label className={styles.labelTtl} for="theirName">User's name</label>
            <input type="text" id="theirName"></input>
          </div>

          <div className={styles.optBox}>
            <label className={styles.labelTtl} for="hEnding">happy ending?</label>
            <input type="checkbox" id="hEnding"></input>

          </div>
          <button>Load!</button>

        </div>

        <div id="copyer">
          <h2 className={styles.heady}>Your email</h2>
          <textarea type="text" id="emailDraft" className={styles.draft}></textarea>
        </div>
      </main>

    </div>
  )
}
